[package]
name = "fake-data"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
fake = { version = "4.3.0", features = [ "derive", "time", "uuid", "email_address" ] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
